const SITTERS = [
  {
    id: 1,
    name: "Sophie Laurent",
    initials: "SL",
    avatarColor: "#1D9E75",
    city: "Austin, TX",
    neighborhood: "Travis Heights",
    bio: "I've dedicated 5 years to caring for pets with special emotional needs. My calm, quiet apartment is a sanctuary for anxious or sensitive animals. I work fully remote and maintain every pet's exact routine with precision. No other animals in my home — your pet gets complete, undivided attention.",
    environmentType: "Quiet apartment",
    otherPets: "None",
    homeAllDay: true,
    yearsExperience: 5,
    numberOfStays: 87,
    rating: 4.97,
    services: ["sitting"],
    walkingRate: null,
    traitScores: {
      anxious: 95,
      social: 60,
      highEnergy: 35,
      shy: 92,
      senior: 88,
      separationAnxiety: 94,
      rescueTrauma: 90,
      playful: 52
    },
    environmentTags: ["only pet", "calm/quiet", "sitter home all day"],
    specialties: ["Separation anxiety", "Senior care", "Shy & timid pets"]
  },
  {
    id: 2,
    name: "Marcus Webb",
    initials: "MW",
    avatarColor: "#F59E0B",
    city: "Denver, CO",
    neighborhood: "Washington Park",
    bio: "Certified dog trainer with 8 years of experience. My large fenced garden and twice-daily run schedule are built for high-energy breeds who need real exercise. I treat training as part of care — every stay reinforces good habits and keeps active dogs genuinely happy.",
    environmentType: "House with large garden",
    otherPets: "One friendly Labrador",
    homeAllDay: false,
    yearsExperience: 8,
    numberOfStays: 203,
    rating: 4.91,
    services: ["sitting", "walking"],
    walkingRate: 18,
    traitScores: {
      anxious: 48,
      social: 88,
      highEnergy: 98,
      shy: 42,
      senior: 52,
      separationAnxiety: 58,
      rescueTrauma: 62,
      playful: 96
    },
    environmentTags: ["garden access", "dog-friendly"],
    specialties: ["High-energy breeds", "Training reinforcement", "Active lifestyle"]
  },
  {
    id: 3,
    name: "Emma Thornton",
    initials: "ET",
    avatarColor: "#8B5CF6",
    city: "Portland, OR",
    neighborhood: "Alberta Arts District",
    bio: "Former rescue volunteer with 7 years rehabilitating traumatised dogs and cats. I understand triggers, body language, and the slow trust-building rescue pets need. My structured, calm home has no children or loud activity — just patience, routine, and unconditional care.",
    environmentType: "Quiet flat",
    otherPets: "One calm senior cat",
    homeAllDay: true,
    yearsExperience: 7,
    numberOfStays: 142,
    rating: 4.99,
    services: ["sitting"],
    walkingRate: null,
    traitScores: {
      anxious: 88,
      social: 70,
      highEnergy: 52,
      shy: 85,
      senior: 80,
      separationAnxiety: 88,
      rescueTrauma: 98,
      playful: 68
    },
    environmentTags: ["calm/quiet", "sitter home all day", "no small children"],
    specialties: ["Rescue & trauma", "Rehabilitation", "Anxious pets"]
  },
  {
    id: 4,
    name: "David Chen",
    initials: "DC",
    avatarColor: "#EF4444",
    city: "Seattle, WA",
    neighborhood: "Queen Anne",
    bio: "Retired vet nurse with 12 years of clinical experience. I specialise in senior pets and those requiring medication administration — insulin, post-surgical recovery, mobility support. My quiet home has no other animals and I'm always present. Medical needs aren't a challenge; they're my speciality.",
    environmentType: "Peaceful detached house",
    otherPets: "None",
    homeAllDay: true,
    yearsExperience: 12,
    numberOfStays: 318,
    rating: 5.0,
    services: ["sitting"],
    walkingRate: null,
    traitScores: {
      anxious: 85,
      social: 62,
      highEnergy: 42,
      shy: 86,
      senior: 99,
      separationAnxiety: 90,
      rescueTrauma: 82,
      playful: 48
    },
    environmentTags: ["only pet", "calm/quiet", "sitter home all day", "no small children"],
    specialties: ["Senior pets", "Medication admin", "Medical needs"]
  },
  {
    id: 5,
    name: "Aria Patel",
    initials: "AP",
    avatarColor: "#EC4899",
    city: "Chicago, IL",
    neighborhood: "Wicker Park",
    bio: "Social, energetic, and always ready for adventure. My resident dog Biscuit loves welcoming new friends, and we head to the dog park every single morning. If your dog is confident, loves other dogs, and has energy to burn — we are absolutely your match.",
    environmentType: "House with fenced yard",
    otherPets: "One playful Beagle mix",
    homeAllDay: false,
    yearsExperience: 3,
    numberOfStays: 64,
    rating: 4.88,
    services: ["sitting", "walking"],
    walkingRate: 15,
    traitScores: {
      anxious: 38,
      social: 98,
      highEnergy: 85,
      shy: 32,
      senior: 42,
      separationAnxiety: 52,
      rescueTrauma: 48,
      playful: 95
    },
    environmentTags: ["dog-friendly", "garden access"],
    specialties: ["Social dogs", "Multi-dog play", "High energy fun"]
  },
  {
    id: 6,
    name: "James O'Brien",
    initials: "JO",
    avatarColor: "#06B6D4",
    city: "Nashville, TN",
    neighborhood: "East Nashville",
    bio: "Our whole family loves dogs — and it shows. With a large garden, a friendly resident dog, and years hosting dogs of every temperament, we're a warm, reliable all-rounder home. I adapt to your pet's routine and keep owners updated with daily photos and check-in messages.",
    environmentType: "Large family home with garden",
    otherPets: "One gentle Golden Retriever",
    homeAllDay: false,
    yearsExperience: 4,
    numberOfStays: 95,
    rating: 4.93,
    services: ["sitting", "walking"],
    walkingRate: 16,
    traitScores: {
      anxious: 70,
      social: 80,
      highEnergy: 75,
      shy: 65,
      senior: 70,
      separationAnxiety: 68,
      rescueTrauma: 65,
      playful: 82
    },
    environmentTags: ["garden access", "dog-friendly"],
    specialties: ["Family environment", "All breeds welcome", "Daily photo updates"]
  }
];
